-- SQL to insert Double Room property in Approved
-- Copy and paste this into Supabase SQL Editor

INSERT INTO properties (
  title,
  description,
  city,
  neighborhood,
  type,
  bedrooms,
  bathroom,
  price,
  deposit,
  water_included,
  electricity_cost,
  available,
  landlord_name,
  landlord_phone,
  whatsapp_number,
  images,
  features,
  nearby_places,
  phone_verified,
  id_verified,
  address_verified,
  rentalke_visited,
  video_url,
  water_source,
  water_payment,
  electricity_type,
  electricity_payment,
  security_type,
  security_details
) VALUES (
  'Affordable Double Room in Approved - Gated with Security',
  'Spacious double room (2 conjoined rooms) in a secure gated compound at Approved, Unik stage. Perfect for singles or students looking for affordable housing. Water included in rent, electricity separate (own meter). Tarmac road access with direct transport to ferry just 2 minutes walk from the property. 10-15 minutes from main road. Ksh 30 fare from Ferry. Security dog on premises and landlord lives next door for easy contact and quick assistance. Peaceful neighborhood with good transport links.',
  'Mombasa',
  'Approved',
  'Double Room',
  '2 rooms',
  'Shared bathroom',
  5000,
  5000,
  true,
  null,
  true,
  'Bichanga',
  '+254707240014',
  '+254707240014',
  ARRAY[
    'https://res.cloudinary.com/dqmnuxht6/image/upload/v1769979253/main-door_fheiag.jpg',
    'https://res.cloudinary.com/dqmnuxht6/image/upload/v1769979253/double-room_xtcyei.jpg',
    'https://res.cloudinary.com/dqmnuxht6/image/upload/v1769979253/corridor-toilet_iqmi2b.jpg'
  ],
  ARRAY[]::text[],
  ARRAY[]::text[],
  true,
  false,
  true,
  true,
  'https://res.cloudinary.com/dqmnuxht6/video/upload/v1769980260/double-room_t5vpo0.mp4',
  'piped_to_house',
  'included_in_rent',
  'prepaid_meter',
  'tenant',
  'gated_compound',
  'Secure gated compound with security dog. Landlord lives next door for easy contact and assistance.'
);
